### ISSUE TITLE
License for COGENT?

### ISSUE THREAD

**Issue by bendudson** [LLNL/COGENT#3]
What license is COGENT available under? The NOTICE file has a disclaimer and notification requirement for commercial use. If it has a standard license then it should be in a LICENSE file in the root directory. 

It looks like Chombo is under a variation on the BSD 3-clause license (https://github.com/LLNL/COGENT/blob/master/Chombo/Copyright.txt).

**Comment by milodorr** [comment]
Ben,

It's a BSD open source license.  Thanks for pointing out the lack of a LICENSE file.  It's there now.

-Milo

________________________________________
From: Ben Dudson ***@***.***>
Sent: Thursday, July 25, 2024 6:33 PM
To: LLNL/COGENT
Cc: Subscribed
Subject: [LLNL/COGENT] License for COGENT? (Issue #3)

What license is COGENT available under? The NOTICE file has a disclaimer and notification requirement for commercial use. If it has a standard license then it should be in a LICENSE file in the root directory.

It looks like Chombo is under a variation on the BSD 3-clause license (https://github.com/LLNL/COGENT/blob/master/Chombo/Copyright.txt<https://urldefense.us/v3/__https://github.com/LLNL/COGENT/blob/master/Chombo/Copyright.txt__;!!G2kpM7uM-TzIFchu!3igiaAnTai1UU6Yp2BQrmfXjyl3-z4mlX45k2fSVmucL3V0MC1lUx_FPv2X3DBJSwMKXyVxEBU3_CcjGjyD6Xv8$>).

**Comment by bendudson** [comment]
Thanks @milodorr !
